import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import SideNav from "./dashboard/_components/SideNav";
import Header from "./dashboard/_components/Header";

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Content Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className={inter.className}>
          <div className='bg-slate-100 h-screen'>
            <div className="md:w-64 md:block hidden fixed">
              <SideNav />
            </div>
            
              {children}
           
          </div>
        </body>
      </html>
  );
}
